### ISSUE TITLE
Instant Launch

### ISSUE THREAD

**Issue by JAJames** [TotemArts/Rx_Launcher#6]
As a player, I would like to be able to immediately launch the game client when I startup the Renegade X launcher.

Acceptance Criteria:
- [ ] Functionality can be toggled via "Instant Launch" launcher setting
- [ ] Functionality is disabled by default
- [ ] Command line option to forcefully disable this option

**Comment by AlienXAXS** [comment]
Could you elaborate on the benefits of doing this, as i see no benefit at all?

If anything it would be more of an issue when you decide to switch back to normal mode, having to tell players to "start the launcher with a command line".

If this is really necessary then perhaps an extra dialog that only appears in this mode that shows "Standby Commander" which will start the game in x seconds, otherwise they can click a button to cancel this feature once it's turned on.

**Comment by JAJames** [comment]
Yeah, you're probably right -- this was one of those not-so-fleshed-out ideas I had posted on the Trello and wasn't sure if it would actually ever get implemented.
